### ISSUE TITLE
Redesign header

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/complainbos-web#18]
- [x] Remove background graphic
- [x] Redesign the header 

![image](https://user-images.githubusercontent.com/30463117/184385717-6a689906-ca3a-45e1-a0d5-4c68994a198d.png)

**Comment by russel0907** [comment]
![Complainbos-Customer-complaint-management-system](https://user-images.githubusercontent.com/94702093/184634170-4635deb5-837e-49bf-ba1c-67e498e07f01.png)
