### ISSUE TITLE
Adjust header for mobile view

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/complainbos-web#30]
![image](https://user-images.githubusercontent.com/30463117/184787050-ad4a02db-8b80-4b50-b7bf-1972bc338514.png)

**Comment by russel0907** [comment]
![Screenshot 2022-08-17 at 10-12-04 Complainbos Customer complaint management system](https://user-images.githubusercontent.com/94702093/185019433-0af4fc80-4279-4bae-bccc-daaf676f29c2.png)
