### ISSUE TITLE
Update screenshot features

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/complainbos-web#38]
![image](https://user-images.githubusercontent.com/30463117/185023507-844da2d4-2e1e-4530-acb0-3cd321a6dd2f.png)

Complainbos is a complaint management system that helps businesses to view, track, and store information about customer queries, resolutions, and follow-up actions in a centralized repository for future reference. The platform enables organizations to manage complaints from customers, and other stakeholders through a unified portal.

**(1) Complaint Submission**
Our complaint management system has all the necessary tools for feedback and complain management for a wide range of industries. Provide a seamless complaint submission cycle for your customers through a convenient scan and submit method. Resolve individual complaints and create potential for systemic improvement.

**(2) Performance Dashboard**
The dashboard allows users to measure results and gain insights into metrics related to complaint submitted by departments in monthly or daily basis, customers, agent performance, and other factors via key performance indicators (KPIs) in real-time. It also offers features such as offline access, root cause analysis, audit trail, and many others.

(3) Reporting 
Addressing and resolving submitted complaints is critical, but being able to spot problem areas and prevent further incidents can also make your organization a better place to work for every employee. Using maps, charts and graphs, you can identify patterns and hotspots so you can stop issues before they start. 

(4) Online Platform
A web-enabled, mobile-friendly platform ensures you capture every complaint. Not only can public submit complaints from wherever they have an internet connection by scanning through the QR code, organisation can make updates and solve tickets anywhere, anytime. This allows you to log information and evidence while it’s still fresh.

**Comment by russel0907** [comment]
![Screenshot 2022-08-17 at 20-32-03 Complainbos Customer complaint management system](https://user-images.githubusercontent.com/94702093/185124853-b8d0e963-ed31-4c00-8775-3aeb8ff72392.png)
