### ISSUE TITLE
website copywriting

### ISSUE THREAD

**Issue by paragasu** [phisoft/complainbos-web#4]

**Comment by rosclaritha** [comment]
Write the copywriting content on the comment. You can view the following issue https://github.com/phisoft/gourbanbus-web/issues/6 to see how I previously did for another website.

**Comment by Suzitaothman** [comment]
Title: **FILE A COMPLAINT**

Caption: Faced a problem or unsatisfied with the services? File a **complaint** to let us know the issues!

We provide this platform for you to submitt any complaints related to our services if there any unsatisfied experience you faced during........

**LIST OF SERVICES OFFERED**
1.
2.

**Track status**
You are able to track the status of your complaint by clicking this............
