### ISSUE TITLE
change logo

### ISSUE THREAD

**Issue by paragasu** [phisoft/complainbos-web#5]
- [x] change logo
- [x] change system screenshots 
![image](https://user-images.githubusercontent.com/30463117/184277219-ca55cc0e-2bdd-4bf9-b97c-1d513e8a82c8.png)

![image](https://user-images.githubusercontent.com/30463117/184277264-9367c014-27c2-4f44-8421-7eda7cd3ab0f.png)

**Comment by russel0907** [comment]
![Complainbos-Customer-complaint-management-system](https://user-images.githubusercontent.com/94702093/184321448-0e859b4d-18b3-4462-9e53-a6a3a837498f.png)
